version: '3'

volumes:
  pg_dat_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_dat_production:/var/lib/postgresql/data

  backend:
    image: ymrmld/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static

  frontend:
    image: ymrmld/taski_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: ymrmld/taski_gateway 
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
